name: build
# on:
#   push:
#     tags:
#       - '*'
on:
  push:
    branches: [ main ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
    - uses: actions/checkout@v2

    # Used to host cibuildwheel
    - uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch -f https://download.pytorch.org/whl/torch_stable.html
        pip install '.[dev]'

    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==2.2.0b1

    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse

    - uses: actions/upload-artifact@v2
      with:
        path: ./wheelhouse/*.whl